/*
 * Class: DIT/FT/1B/03
 * Admission Number: 2026453
 * Name:Phan Kiah Fong Nicholas
 */
package JPRG;

import java.io.*;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author nicho
 */
public class GUI extends javax.swing.JFrame {

    private EventManagement events = new EventManagement();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Displaybtn = new javax.swing.JButton();
        Displaybtn1 = new javax.swing.JButton();
        Displaybtn2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        searchFeesTxt = new javax.swing.JTextField();
        searchFeesBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        eventNameTxt = new javax.swing.JTextField();
        searchNameBtn = new javax.swing.JButton();
        registerEventBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        adminButton = new javax.swing.JRadioButton();
        userButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        NAME = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        ORGANIZER = new javax.swing.JLabel();
        orgTxt = new javax.swing.JTextField();
        FEES = new javax.swing.JLabel();
        feesTxt = new javax.swing.JTextField();
        DNT = new javax.swing.JLabel();
        dntTxt = new javax.swing.JTextField();
        onlineBtn = new javax.swing.JRadioButton();
        F2FBtn = new javax.swing.JRadioButton();
        addEventBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        TIME = new javax.swing.JLabel();
        timeTxt = new javax.swing.JTextField();
        LIMIT = new javax.swing.JLabel();
        limitTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResults = new javax.swing.JTextArea();
        eventDetailsButton = new javax.swing.JButton();
        currentDNT = new javax.swing.JTextField();
        currentDNTBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Displaybtn.setBackground(java.awt.Color.blue);
        Displaybtn.setForeground(java.awt.Color.white);
        Displaybtn.setText("Display Events");
        Displaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaybtnActionPerformed(evt);
            }
        });

        Displaybtn1.setBackground(java.awt.Color.blue);
        Displaybtn1.setForeground(java.awt.Color.white);
        Displaybtn1.setText("Reset");
        Displaybtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Displaybtn1ActionPerformed(evt);
            }
        });

        Displaybtn2.setBackground(java.awt.Color.blue);
        Displaybtn2.setForeground(java.awt.Color.white);
        Displaybtn2.setText("Exit");
        Displaybtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Displaybtn2ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setText("Event Fees ($):");

        searchFeesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFeesTxtActionPerformed(evt);
            }
        });

        searchFeesBtn.setBackground(java.awt.Color.lightGray);
        searchFeesBtn.setText("Search by Fees");
        searchFeesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFeesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchFeesTxt)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(searchFeesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addComponent(searchFeesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchFeesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel9.setText("Event Name:");

        eventNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventNameTxtActionPerformed(evt);
            }
        });

        searchNameBtn.setText("Search by Name");
        searchNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameBtnActionPerformed(evt);
            }
        });

        registerEventBtn.setBackground(new java.awt.Color(255, 51, 51));
        registerEventBtn.setText("Register Event");
        registerEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerEventBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addComponent(eventNameTxt)
                    .addComponent(registerEventBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchNameBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchNameBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerEventBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Event Management System");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("User Type"));

        buttonGroup1.add(adminButton);
        adminButton.setText("Administrator");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(userButton);
        userButton.setSelected(true);
        userButton.setText("Normal User");
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(adminButton)
                .addGap(60, 60, 60)
                .addComponent(userButton)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userButton)
                    .addComponent(adminButton))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Add / Delete Event"));

        NAME.setText("Name:");

        nameTxt.setEditable(false);
        nameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nameTxtMouseEntered(evt);
            }
        });
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        ORGANIZER.setText("Organizer:");

        orgTxt.setEditable(false);
        orgTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orgTxtMouseEntered(evt);
            }
        });
        orgTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgTxtActionPerformed(evt);
            }
        });

        FEES.setText("Fees:");

        feesTxt.setEditable(false);
        feesTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                feesTxtMouseEntered(evt);
            }
        });
        feesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feesTxtActionPerformed(evt);
            }
        });

        DNT.setText("Date & Time:");

        dntTxt.setEditable(false);
        dntTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dntTxtMouseEntered(evt);
            }
        });
        dntTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dntTxtActionPerformed(evt);
            }
        });

        buttonGroup2.add(onlineBtn);
        onlineBtn.setSelected(true);
        onlineBtn.setText("Online Event");
        onlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlineBtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(F2FBtn);
        F2FBtn.setText("Face to Face Event");
        F2FBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F2FBtnActionPerformed(evt);
            }
        });

        addEventBtn.setText("Add Event");
        addEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEventBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Delete Event");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        TIME.setText("Time(24hrs):");

        timeTxt.setEditable(false);
        timeTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                timeTxtMouseEntered(evt);
            }
        });
        timeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTxtActionPerformed(evt);
            }
        });

        LIMIT.setText("Limit:");

        limitTxt.setEditable(false);
        limitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                limitTxtMouseEntered(evt);
            }
        });
        limitTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(onlineBtn)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(addEventBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delBtn)
                            .addComponent(F2FBtn)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DNT)
                            .addComponent(FEES)
                            .addComponent(ORGANIZER)
                            .addComponent(NAME)
                            .addComponent(TIME)
                            .addComponent(LIMIT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeTxt)
                            .addComponent(nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(orgTxt)
                            .addComponent(feesTxt)
                            .addComponent(dntTxt)
                            .addComponent(limitTxt))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAME)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ORGANIZER, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FEES)
                    .addComponent(feesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNT)
                    .addComponent(dntTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TIME)
                    .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LIMIT)
                    .addComponent(limitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(F2FBtn)
                    .addComponent(onlineBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delBtn)
                    .addComponent(addEventBtn))
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Results:");

        txtResults.setEditable(false);
        txtResults.setColumns(20);
        txtResults.setRows(5);
        jScrollPane1.setViewportView(txtResults);

        eventDetailsButton.setText("Event Details");
        eventDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventDetailsButtonActionPerformed(evt);
            }
        });

        currentDNT.setEditable(false);
        currentDNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentDNTActionPerformed(evt);
            }
        });

        currentDNTBtn.setText("Display Current Date & Time");
        currentDNTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentDNTBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(currentDNTBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(currentDNT, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Displaybtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Displaybtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eventDetailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(423, 423, 423))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Displaybtn)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(currentDNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Displaybtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(currentDNTBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(eventDetailsButton)
                        .addGap(59, 59, 59)
                        .addComponent(Displaybtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Displaybtn2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaybtnActionPerformed
//        Displaybtn.setBackground(Color.blue);
//        events.displayEvent();
        txtResults.setText(events.displayEvent());
    }//GEN-LAST:event_DisplaybtnActionPerformed

    private void Displaybtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Displaybtn1ActionPerformed
        nameTxt.setText("");
        orgTxt.setText("");
        feesTxt.setText("");
        dntTxt.setText("");
        searchFeesTxt.setText("");
        eventNameTxt.setText("");
        timeTxt.setText("");
        txtResults.setText("");
        limitTxt.setText("");
    }//GEN-LAST:event_Displaybtn1ActionPerformed

    private void Displaybtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Displaybtn2ActionPerformed
        System.out.println("You have exited the program!");
        System.exit(0);
    }//GEN-LAST:event_Displaybtn2ActionPerformed

    private void searchFeesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFeesBtnActionPerformed
        try {
            String feesStr = searchFeesTxt.getText();
            double fees = Double.parseDouble(feesStr);
//        JOptionPane.showMessageDialog(null, events.searchEventByFees(fees))
            txtResults.setText(events.searchEventByFees(fees));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Please input a number!");
        }
    }//GEN-LAST:event_searchFeesBtnActionPerformed

    private void eventNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventNameTxtActionPerformed

    private void searchNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameBtnActionPerformed

        txtResults.setText(events.searchEventByName(eventNameTxt.getText()));
    }//GEN-LAST:event_searchNameBtnActionPerformed

    private void registerEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerEventBtnActionPerformed
//        Displaybtn.setBackground(Color.red);
        String register = eventNameTxt.getText();
        txtResults.setText(events.registerEvent(register));
    }//GEN-LAST:event_registerEventBtnActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
//        ButtonGroup bG1 = new ButtonGroup();
//        bG1.add(btn1);
//        bG1.add(btn2);
        if (adminButton.isSelected()) {

            nameTxt.setEditable(true);
            orgTxt.setEditable(true);
            feesTxt.setEditable(true);
            dntTxt.setEditable(true);
            timeTxt.setEditable(true);
            addEventBtn.setEnabled(true);
            delBtn.setEnabled(true);
            registerEventBtn.setEnabled(false);
        }

    }//GEN-LAST:event_adminButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        if (userButton.isSelected()) {
            nameTxt.setEditable(false);
            orgTxt.setEditable(false);
            feesTxt.setEditable(false);
            dntTxt.setEditable(false);
            timeTxt.setEditable(false);
            addEventBtn.setEnabled(false);
            delBtn.setEnabled(false);
            registerEventBtn.setEnabled(true);

        }

    }//GEN-LAST:event_userButtonActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
    }//GEN-LAST:event_nameTxtActionPerformed

    private void orgTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgTxtActionPerformed

    private void feesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feesTxtActionPerformed

    private void dntTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dntTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dntTxtActionPerformed

    private void onlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlineBtnActionPerformed
//        ButtonGroup bG2 = new ButtonGroup();
//        bG2.add(Eventbtn1);
//        bG2.add(Eventbtn2);
//        Eventbtn1.setSelected(true);
        if (onlineBtn.isSelected()) {
            limitTxt.setEditable(false);
            limitTxt.setEnabled(false);
        }

    }//GEN-LAST:event_onlineBtnActionPerformed

    private void F2FBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F2FBtnActionPerformed
        if (F2FBtn.isSelected() && adminButton.isSelected()) {
            limitTxt.setEditable(true);
            limitTxt.setEnabled(true);
        }
    }//GEN-LAST:event_F2FBtnActionPerformed

    private void addEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEventBtnActionPerformed

        if (adminButton.isSelected() && onlineBtn.isSelected()) {
            try {
                limitTxt.setText("0");
                String eventName = nameTxt.getText();
                String newOrganizer = orgTxt.getText();
                String newDNT = dntTxt.getText();
                String newTimeStr = timeTxt.getText();
                String newDoubleFeesStr = feesTxt.getText();
                String newLimitStr = limitTxt.getText();
                int limit = Integer.parseInt(newLimitStr);
                boolean type = onlineBtn.isSelected();
                int newTime = Integer.parseInt(newTimeStr);
                Double newDoubleFees = Double.parseDouble(newDoubleFeesStr);
//                while (limit < 0 || newDoubleFees < 0) {
//                    JOptionPane.showMessageDialog(null, "Please enter a positive value!");
//                    newTimeStr = timeTxt.getText();
//                    newTime = Integer.parseInt(newLimitStr);
//                    newLimitStr = limitTxt.getText();
//                    limit = Integer.parseInt(newLimitStr);
//                }
                if (limit < 0 || newDoubleFees < 0) {
                    throw new IllegalArgumentException("Please enter a valid number!");
                }
                txtResults.setText(events.addEvent(eventName, newOrganizer, newDNT, newTime, newDoubleFees, type, limit));

            } catch (NumberFormatException ex) {
                txtResults.setText("Please enter the correct details!");
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(null, "Please input a valid number!!");
            } catch (Exception e) {
                txtResults.setText("Unknown Error!");
            }
        } else if (adminButton.isSelected() && F2FBtn.isSelected()) {
            try {
                String eventName = nameTxt.getText();
                String newOrganizer = orgTxt.getText();
                String newDNT = dntTxt.getText();
                String newTimeStr = timeTxt.getText();
                String newDoubleFeesStr = feesTxt.getText();
                String newLimitStr = limitTxt.getText();
                int limit = Integer.parseInt(newLimitStr);
                boolean type = onlineBtn.isSelected();
                int newTime = Integer.parseInt(newTimeStr);
                Double newDoubleFees = Double.parseDouble(newDoubleFeesStr);
                if (limit < 0 || newDoubleFees < 0) {
                    throw new IllegalArgumentException("Please enter a valid number!");
                }
                txtResults.setText(events.addEvent(eventName, newOrganizer, newDNT, newTime, newDoubleFees, type, limit));
            } catch (NumberFormatException ex) {
                txtResults.setText("Please enter the correct details!");
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(null, "Please input a valid number!!");
            } catch (Exception e) {
                txtResults.setText("Unknown Error!");
            }
        }
    }//GEN-LAST:event_addEventBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        txtResults.setText(events.deleteEvent(nameTxt.getText()));
    }//GEN-LAST:event_delBtnActionPerformed

    private void searchFeesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFeesTxtActionPerformed

    }//GEN-LAST:event_searchFeesTxtActionPerformed

    private void timeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTxtActionPerformed

    private void limitTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limitTxtActionPerformed

    private void eventDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventDetailsButtonActionPerformed
        txtResults.setText(events.displayEventMessage());

    }//GEN-LAST:event_eventDetailsButtonActionPerformed

    private void timeTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeTxtMouseEntered
        timeTxt.setToolTipText("Please enter the numbers in this format (XXXX)");
    }//GEN-LAST:event_timeTxtMouseEntered

    private void currentDNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentDNTActionPerformed
        currentDNT.setText(events.displayCurrentDate());


    }//GEN-LAST:event_currentDNTActionPerformed

    private void currentDNTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentDNTBtnActionPerformed
        currentDNT.setText(events.displayCurrentDate());
    }//GEN-LAST:event_currentDNTBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        InputStream music;
        try {
            music = new FileInputStream(new File("C:\\Users\\nicho\\Dropbox\\My PC (LAPTOP-AE9RFCDD)\\Documents\\NetBeansProjects\\JAVA2Assignment\\src\\JPRG\\COMCell_Message 1 (ID 1111)_BSB.wav"));
            AudioStream audios = new AudioStream(music);
            AudioPlayer.player.start(audios);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void nameTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTxtMouseEntered
        nameTxt.setToolTipText("Please enter the event name");
    }//GEN-LAST:event_nameTxtMouseEntered

    private void orgTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orgTxtMouseEntered
        orgTxt.setToolTipText("Please enter the organization");
    }//GEN-LAST:event_orgTxtMouseEntered

    private void feesTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feesTxtMouseEntered
        feesTxt.setToolTipText("Please enter the fees for this event");
    }//GEN-LAST:event_feesTxtMouseEntered

    private void dntTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dntTxtMouseEntered
        dntTxt.setToolTipText("Please enter the date of event (e.g. 13-Dec-2020)");
    }//GEN-LAST:event_dntTxtMouseEntered

    private void limitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limitTxtMouseEntered
        limitTxt.setToolTipText("Please enter the limit if it is a face to face event. Or else there will not be any limit!");
    }//GEN-LAST:event_limitTxtMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNT;
    private javax.swing.JButton Displaybtn;
    private javax.swing.JButton Displaybtn1;
    private javax.swing.JButton Displaybtn2;
    private javax.swing.JRadioButton F2FBtn;
    private javax.swing.JLabel FEES;
    private javax.swing.JLabel LIMIT;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel ORGANIZER;
    private javax.swing.JLabel TIME;
    private javax.swing.JButton addEventBtn;
    private javax.swing.JRadioButton adminButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField currentDNT;
    private javax.swing.JButton currentDNTBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JTextField dntTxt;
    private javax.swing.JButton eventDetailsButton;
    private javax.swing.JTextField eventNameTxt;
    private javax.swing.JTextField feesTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField limitTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JRadioButton onlineBtn;
    private javax.swing.JTextField orgTxt;
    private javax.swing.JButton registerEventBtn;
    private javax.swing.JButton searchFeesBtn;
    private javax.swing.JTextField searchFeesTxt;
    private javax.swing.JButton searchNameBtn;
    private javax.swing.JTextField timeTxt;
    private javax.swing.JTextArea txtResults;
    private javax.swing.JRadioButton userButton;
    // End of variables declaration//GEN-END:variables
}
